### ISSUE TITLE
علاقه مند

### ISSUE THREAD

**Issue by mehrdad-dev** [frezaeix/Reading_group_persian#1]
سلام مرسی از این حرکت خوبتون :)
من مهرداد ام دانشجو سال آخر کارشناسی مهندسی کامپیوتر
دارم سعی میکنم یک مقاله در حوزه computer vision بدم.
و روی یک مقاله دیگه توی حوزه منطق فازی هم کار میکنم، که بشه پروژه کارشناسی ... .
از لحاظ علم نوشتن خود مقاله و این چیزا خیلی مبتدی ام، و دوست دارم واقعا از تجربه ها و نکته های بقیه استفاده کنم
از اون لیست نامبرده شده هم به ۲ تا اولی علاقه دارم، در مورد فیو شات لرنینگ هم خیلی مطالعه نداشتم

**Comment by frezaeix** [comment]
> سلام مرسی از این حرکت خوبتون :) من مهرداد ام دانشجو سال آخر کارشناسی مهندسی کامپیوتر دارم سعی میکنم یک مقاله در حوزه computer vision بدم. و روی یک مقاله دیگه توی حوزه منطق فازی هم کار میکنم، که بشه پروژه کارشناسی ... . از لحاظ علم نوشتن خود مقاله و این چیزا خیلی مبتدی ام، و دوست دارم واقعا از تجربه ها و نکته های بقیه استفاده کنم از اون لیست نامبرده شده هم به ۲ تا اولی علاقه دارم، در مورد فیو شات لرنینگ هم خیلی مطالعه نداشتم

<div dir="rtl">
سلام مرسی و خوش آمدید ویژه به عنوان اولین نفر :)
میتونین مقالاتی که تا الان خوندین یا دوست دارین رو اینجا به اشتراک بذارین تا کم کم ببینیم علاقه و جهت به کدوم سمته
من خودم به عنوان شروع  این لینک رو میذارم که فعلا روش تمرکز بیشتری دارم اما بیشتر موافق مقالات جدیدتر هستم.
</div>

[link to papers](https://github.com/frezaeix/3D_Object_Detection)

**Comment by mehrdad-dev** [comment]
> > سلام مرسی از این حرکت خوبتون :) من مهرداد ام دانشجو سال آخر کارشناسی مهندسی کامپیوتر دارم سعی میکنم یک مقاله در حوزه computer vision بدم. و روی یک مقاله دیگه توی حوزه منطق فازی هم کار میکنم، که بشه پروژه کارشناسی ... . از لحاظ علم نوشتن خود مقاله و این چیزا خیلی مبتدی ام، و دوست دارم واقعا از تجربه ها و نکته های بقیه استفاده کنم از اون لیست نامبرده شده هم به ۲ تا اولی علاقه دارم، در مورد فیو شات لرنینگ هم خیلی مطالعه نداشتم
> 
> سلام مرسی و خوش آمدید ویژه به عنوان اولین نفر :) میتونین مقالاتی که تا الان خوندین یا دوست دارین رو اینجا به اشتراک بذارین تا کم کم ببینیم علاقه و جهت به کدوم سمته من خودم به عنوان شروع این لینک رو میذارم که فعلا روش تمرکز بیشتری دارم اما بیشتر موافق مقالات جدیدتر هستم.
> [link to papers](https://github.com/frezaeix/3D_Object_Detection)


ممنون =)))
اکثر چیز هایی که من خوندم معماری های معروف بودن، مثل:

**object detection:**
- YOLO
- SSD
- R-CNN

**image segmentation:**
- Unet

و MobileNet

و الان هم بیشتر روی  mobile net و unet تمرکز کردم.
